"""
Repository protocol definitions for type safety and dependency injection.
"""

from typing import Any, Protocol, runtime_checkable

from backend.schemas.schemas import (
    CommentResponse,
    MessageResponse,
    MovieResponse,
    UserCreate,
    UserResponse,
)


@runtime_checkable
class RepositoryProtocol(Protocol):
    """Protocol defining the interface for repository operations."""

    database_name: str
    collection_name: str

    async def _find_by_id(self, id: str) -> dict[str, Any] | None: ...
    async def _find_many(
        self,
        filter_query: dict[str, Any] | None = None,
        limit: int = 10,
        skip: int = 0,
        **kwargs,
    ) -> list[dict[str, Any]]: ...
    async def _find_distinct(
        self, field: str, filter_query: dict[str, Any] | None = None
    ) -> list[str]: ...
    async def _create_one(self, document: dict[str, Any]) -> str | None: ...
    async def _update_one(
        self, filter_query: dict[str, Any], update_query: dict[str, Any]
    ) -> int | None: ...
    async def _update_many(
        self, filter_query: dict[str, Any], update_query: dict[str, Any]
    ) -> int | None: ...
    async def _delete_many(self, filter_query: dict[str, Any]) -> int | None: ...


@runtime_checkable
class MovieRepositoryProtocol(RepositoryProtocol, Protocol):
    """Protocol for movie-specific repository operations."""

    async def search_movies(self, **kwargs) -> list[MovieResponse]: ...
    async def search_movies_by_text(
        self, search_text: str, **kwargs
    ) -> list[MovieResponse]: ...
    async def find_by_id(self, id: str, **kwargs) -> MovieResponse | None: ...
    async def find_by_type(
        self, type: str, include_invalid_posters: bool = False, **kwargs
    ) -> list[MovieResponse]: ...
    async def find_by_year(
        self, year: int, mod: str, include_invalid_posters: bool = False, **kwargs
    ) -> list[MovieResponse]: ...
    async def find_by_rating(
        self, rating: int, mod: str, include_invalid_posters: bool = False, **kwargs
    ) -> list[MovieResponse]: ...
    async def find_by_genre(self, genre: str, **kwargs) -> list[MovieResponse]: ...
    async def get_all_genres(self) -> list[str]: ...
    async def get_all_types(self) -> list[str]: ...


@runtime_checkable
class UserRepositoryProtocol(RepositoryProtocol, Protocol):
    """Protocol for user-specific repository operations."""

    async def search_users(self, **kwargs) -> list[UserResponse]: ...
    async def find_by_id(self, id: str, **kwargs) -> UserResponse | None: ...
    async def find_by_email(self, email: str, **kwargs) -> list[UserResponse]: ...
    async def find_by_name(self, name: str, **kwargs) -> list[UserResponse]: ...
    async def email_exists(self, email: str) -> bool: ...
    async def create_user(self, user_data: UserCreate) -> MessageResponse | None: ...


@runtime_checkable
class CommentRepositoryProtocol(RepositoryProtocol, Protocol):
    """Protocol for comment-specific repository operations."""

    async def search_comments(self, **kwargs) -> list[CommentResponse]: ...
    async def find_by_id(self, id: str, **kwargs) -> CommentResponse | None: ...
    async def find_by_movie_id(
        self, movie_id: str, **kwargs
    ) -> list[CommentResponse]: ...
    async def find_by_email(self, email: str, **kwargs) -> list[CommentResponse]: ...
    async def find_by_name(self, name: str, **kwargs) -> list[CommentResponse]: ...
